Repository LearnWeb3DAO/Freshman-Track, pull requests merged in 2022-12, with the labels that each got.

#6 Added VSCode installation tutorial + fixed typos and markdown coloring.
  Build-your-first-dApp.md
Labels: documentation, question

#22 Fixed item list number order.
  Build-your-first-dApp.md
Labels: documentation

#24 Fixed typos in Intro to Solidity
  Intro-to-Solidity.md
Labels: documentation, good first issue

#25 Fix contract name in comments
  Build-your-own-NFT.md
Labels: documentation, good first issue
