Repository LearnWeb3DAO/Freshman-Track, pull requests merged in 2023-05, with the labels that each got.

#42 minor change: changed solidity version to newer (^0.8.19)
  Build-your-first-dApp.md
  Build-your-own-NFT.md
  Build-your-own-cryptocurrency.md
  Intro-to-Solidity.md
  Remix-IDE.md
Labels: documentation

#43 Update Remix-IDE.md
  Remix-IDE.md
Labels: documentation, good first issue, question

#44 typo in What-is-a-Blockchain.md
  What-is-a-Blockchain.md
Labels: documentation, good first issue
